# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: callalready
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: call-already-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: call-already-api

provider:
  name: aws
  runtime: nodejs20.x
  environment: 
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - ses:*
      Resource: '*'

plugins:
 - serverless-offline

functions:
  validate-group:
    handler: user.validateGroup
    events:
      - httpApi:
          path: /validate-group
          method: get
  create-group:
    handler: user.createGroup
    events:
      - httpApi:
          path: /create-group
          method: post
  post-responses:
    handler: user.postResponses
    events:
      - httpApi:
          path: /post-responses
          method: post

custom:
  tableName: user-groups

resources:
  Resources:
    UsersDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST